name: "Yeti Benchmarks"
app_id: "app-benchmarks"
version: "0.1.0"
customer_id: "yeti"
required_roles: [yeti_admin]

static:
  path: web
  route: /
  spa: true
  build:
    source: source
    command: npm run build

schemas:
  path: schema.graphql

resources:
  path: "resources/*.rs"
  route: /api

binaries:
  - "bin/*.rs"

modules:
  - "modules/*.rs"

authLoader:
  roles: auth/roles.json

auth:
  signup: auto
  default_role: yeti_admin
  methods: [oauth]
  oauth:
    google:
      clientId: "${GOOGLE_CLIENT_ID}"
      clientSecret: "${GOOGLE_CLIENT_SECRET}"
    rules:
      - strategy: email
        pattern: "*@yetirocks.com"
        role: yeti_admin
