type TestRun @table(database: "app-benchmarks") @export(mqtt: false) {
    id: ID!
    testName: String! @indexed
    timestamp: String!
    durationSecs: Float
    clients: Int
    results: String
    summary: String
    snapshots: String
}

type Book @table(database: "app-benchmarks", residency: "sharded") @export(mqtt: false) {
    id: ID!
    title: String!
    isbn: String! @indexed
    genre: String @indexed
    price: Float
    authorId: ID! @indexed
    author: Author @relationship(from: "authorId")
}

type Author @table(database: "app-benchmarks", residency: "sharded") @export(mqtt: false) {
    id: ID!
    name: String!
}

type Article @table(database: "app-benchmarks") @export(mqtt: false) {
    id: ID!
    title: String!
    author: String!
    category: String! @indexed
    content: String!
    embedding: Vector @indexed(source: "content")
}

type Blob @table(database: "app-benchmarks") @export(mqtt: false) {
    id: ID!
    title: String!
    author: String!
    category: String!
    content: String!
}

type Message @table(database: "app-benchmarks") @export(
    rest: true
    sse: true
    ws: true
    mqtt: false
) {
    id: ID!
    title: String!
    content: String!
}
